---
driver:
  name: ec2
  region: us-east-2
  boot_timeout: 1200
  gui: false

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      "*":
        - outlyeragent

platforms:
  - name: ubuntu-1404
    driver:
      box: ubuntu-14.04
      image_id: ami-b2132ed7
  - name: ubuntu-1604
    driver:
      box: ubuntu-16.04
      image_id: ami-916f59f4
  - name: centos-6
    driver:
      box: centos-6
  - name: centos-7
    driver:
      box: centos-7
  - name: debian-8
    driver:
      box: debian-8
  - name: debian-9
    driver:
      box: debian-9

suites:
  - name: default
    provisioner:
      pillars-from-files:
        outlyeragent.sls: pillar-example.sls
      pillars:
        top.sls:
          base:
            "*":
              - outlyeragent
    verifier:
      inspec_tests:
        - test
    attributes:
      outlyer:
        agent:
          agent_key: XXX-XXX-XXX-XXX-XXX
          labels:
            role: test
          package:
            version: 0.0.67-1

verifier:
  name: inspec
