# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      "*":
        - outlyeragent

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.6
  - name: centos-7.2

suites:
  - name: default
    provisioner:
      pillars-from-files:
        outlyeragent.sls: pillar-example.sls
      pillars:
        top.sls:
          base:
            "*":
              - outlyeragent

